{{- $chartContext := . }}
{{- range $location, $selectors := .Values.locations }}
{{- with $chartContext }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-ping.fullname" . }}-{{ $location }}
  labels:
    {{- include "prometheus-ping.labels" . | nindent 4 }}
    location: {{ $location }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "prometheus-ping.selectorLabels" . | nindent 6 }}
      location: {{ $location }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prometheus-ping.selectorLabels" . | nindent 8 }}
        location: {{ $location }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ping
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --source={{ include "prometheus-ping.fullname" . }}-{{ $location }}:5000
          {{- range $otherLoc, $otherSelectors := .Values.locations }}
          {{- if ne $location $otherLoc }}
          {{- with $chartContext }}
            - {{ include "prometheus-ping.fullname" . }}-{{ $otherLoc }}:5000
          {{- end }}
          {{- end }}
          {{- end }}
          ports:
            - name: ping
              containerPort: 5000
              protocol: UDP
            - name: metrics
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "2"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- $selectors | toYaml | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
