apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-ping.fullname" . }}
  labels:
    {{- include "prometheus-ping.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: metrics
  selector:
    {{- include "prometheus-ping.selectorLabels" . | nindent 4 }}
