{{- $chartContext := . }}
{{- range $location, $selectors := .Values.locations }}
{{- with $chartContext }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-ping.fullname" . }}-{{ $location }}
  labels:
    {{- include "prometheus-ping.labels" . | nindent 4 }}
    location: {{ $location }}
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: UDP
      name: ping
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: metrics
  selector:
    {{- include "prometheus-ping.selectorLabels" . | nindent 4 }}
    location: {{ $location }}
{{- end }}
{{- end }}
